name: tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: setting up go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: install dependencies
      run: go mod download

    - name: copy local mango package
      run: |
        mkdir -p ../mango
        cp -r $GOPATH/src/github.com/tagus/mango/ ../mango/

    - name: running all tests
      run: go test -v ./...
      env:
        GO111MODULE: on
